# Your name: James Cole
# Date: September 25, 2023

# sum_to
# calculate and print the sum of all numbers less than or equal to a 
# user-supplied limit
#def sum_to():
   # print(sum(range(1 + int(input("Give me a number ")))))
#sum_to()
# factorial calculator
# Calculates the factorial of a user suplied number
#def fact():
    #fact = 1
    #n = int(input("Give me a number "))
    #for i in range(1, n+1):
        #fact = fact * i
    #print(fact) 
#fact()
# max
# find and print the maximum value in user_list, which will get generated by a
# combination of input and the "split" and "map" functions (which we haven't 
# learned yet)
def max():
    user_list = map(float(input("enter at least two numbers, separated by commas", "(no spaces!)").split(",")))
    print("The higher number is: ", max(user_list))

max()
# mults_till_k
# take in an integer from the user, and print out every multiple of it that
# is less than or equal to 1000.
#def mults_till_k():

# is_palindrome 
# Takes string input from user and checks if the word is a palindrome
#def is_palindrome():
    #word = input("Give me a word I'll check if it's a palindrome ")
    #reverse = word[::-1]
    #if reverse == word:
        #print("this word is a palindrome")
    #else: 
        #print("this word is not a palindrome")
#is_palindrome()
            