# list_loop
# Complete the empty functions below according to the homework specifications
# to practice lists and loops
#
# Please remember that all solutions must use either a loop, a list, or both!
#
# Your name:
# Date:

# sum_to
# calculate and print the sum of all numbers less than or equal to a 
# user-supplied limit
#def sum_to():
   # print(sum(range(1 + int(input("Give me a number ")))))
#sum_to()
# fact
# use a loop to calculate and print the factorial value of a 
# user-supplied number
# e.g. 5! = 5 * 4 * 3 * 2 * 1 = 120
#def fact():
    #fact = 1
    #n = int(input("Give me a number "))
    #for i in range(1, n+1):
        #fact = fact * i
    #print(fact) 
#fact()
# max
# find and print the maximum value in user_list, which will get generated by a
# combination of input and the "split" and "map" functions (which we haven't 
# learned yet)
def max():
    temp_list = int(input("enter at least two numbers, separated by commas",
        "(no spaces!)"))
    user_list = temp_list.split(",")
    user_list = list(map(float, user_list))
    print(user_list)

max()
# mults_till_k
# take in an integer from the user, and print out every multiple of it that
# is less than or equal to 1000.
#def mults_till_k():

# is_palindrome 
# use input to take a string from the user, and use a loop and what you
# know about strings to determine whether the given string is a palindrome
# (which is a string that reads the same forwards and backwards)
# e.g. input of "racecar" will print "true", input of "cat" will print "false"
#def is_palindrome():
